import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Optimus",
  description: "Generated by create next app",
};

import { FocusButton } from "@/components/FocusButton";
import { FocusModeModal } from "@/components/FocusModeModal";
import { AuthProvider } from "@/contexts/AuthContext";
import { FocusModeProvider } from "@/contexts/FocusModeContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthProvider>
          <FocusModeProvider>
            <FocusButton />
            {children}
            <FocusModeModal />
          </FocusModeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
